config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :books
  resources :librarians
  resources :clients
  resources :authors
  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/librarian.rb
class Librarian < ApplicationRecord
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
  before_action :set_librarian, only: [:show, :edit, :update, :destroy]

  # GET /librarians
  # GET /librarians.json
  def index
    @librarians = Librarian.all
  end

  # GET /librarians/1
  # GET /librarians/1.json
  def show
  end

  # GET /librarians/new
  def new
    @librarian = Librarian.new
  end

  # GET /librarians/1/edit
  def edit
  end

  # POST /librarians
  # POST /librarians.json
  def create
    @librarian = Librarian.new(librarian_params)

    respond_to do |format|
      if @librarian.save
        format.html { redirect_to @librarian, notice: 'Librarian was successfully created.' }
        format.json { render :show, status: :created, location: @librarian }
      else
        format.html { render :new }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /librarians/1
  # PATCH/PUT /librarians/1.json
  def update
    respond_to do |format|
      if @librarian.update(librarian_params)
        format.html { redirect_to @librarian, notice: 'Librarian was successfully updated.' }
        format.json { render :show, status: :ok, location: @librarian }
      else
        format.html { render :edit }
        format.json { render json: @librarian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /librarians/1
  # DELETE /librarians/1.json
  def destroy
    @librarian.destroy
    respond_to do |format|
      format.html { redirect_to librarians_url, notice: 'Librarian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_librarian
      @librarian = Librarian.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def librarian_params
      params.require(:librarian).permit(:Name)
    end
end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/_form.html.erb
<%= form_with(model: librarian, local: true) do |form| %>
  <% if librarian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(librarian.errors.count, "error") %> prohibited this librarian from being saved:</h2>

      <ul>
        <% librarian.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/librarians/edit.html.erb
<h1>Editing Librarian</h1>

<%= render 'form', librarian: @librarian %>

<%= link_to 'Show', @librarian %> |
<%= link_to 'Back', librarians_path %>

app/views/librarians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Librarians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @librarians.each do |librarian| %>
      <tr>
        <td><%= librarian.Name %></td>
        <td><%= link_to 'Show', librarian %></td>
        <td><%= link_to 'Edit', edit_librarian_path(librarian) %></td>
        <td><%= link_to 'Destroy', librarian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Librarian', new_librarian_path %>

app/views/librarians/new.html.erb
<h1>New Librarian</h1>

<%= render 'form', librarian: @librarian %>

<%= link_to 'Back', librarians_path %>

app/views/librarians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @librarian.Name %>
</p>

<%= link_to 'Edit', edit_librarian_path(@librarian) %> |
<%= link_to 'Back', librarians_path %>